window.GLOAM_STORE = {
  name: "Gloam",
  email: "khourypaul19@gmail.com",
  currency: "EUR",
  paymentUrl: "",
  shipping: {
    region: "European Union",
    days: "7–14 days typical",
    price: 0,
    note: "Included in the price for EU addresses. A warehouse ships the carton — we do not keep stock.",
  },
  countries: [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
  ],
  products: [
    {
      id: "lamp",
      sku: "GLOAM-LAMP-01",
      name: "Sunset lamp",
      price: 39,
      blurb:
        "A small projector. Plug in USB-C, tilt the head, put a round gold light on the wall. That is the whole catalog.",
      includes: [
        "Matte black sunset projector",
        "USB-C cable",
        "Ships in a plain carton",
      ],
      specs: [
        ["Power", "USB-C, 5V"],
        ["Head", "Tilts 180°"],
        ["Finish", "Matte black"],
        ["Use", "Indoor wall"],
      ],
      images: [
        {
          src: "assets/gloam-hero.jpg",
          alt: "Lamp on a side table projecting a gold circle on the wall",
        },
        {
          src: "assets/gloam-product.jpg",
          alt: "Matte black lamp and USB-C cable",
        },
        {
          src: "assets/gloam-wall.jpg",
          alt: "Close view of the dusk circle on a bedroom wall",
        },
        {
          src: "assets/gloam-contents.jpg",
          alt: "Lamp, cable, and a plain kraft mailer",
        },
      ],
    },
  ],
};
