window.REWRAP = {
  name: "Rewrap",
  email: "khourypaul19@gmail.com",
  currency: "EUR",
  paymentUrl: "",
  shipping: {
    region: "European Union",
    days: "5–12 days typical",
    price: 0,
    note: "In the price for EU. A warehouse posts the sleeve — we don’t keep a box of grips.",
  },
  countries: [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
  ],
  products: [
    {
      id: "sleeve",
      sku: "REWRAP-12",
      name: "The sleeve",
      price: 16,
      blurb:
        "Twelve overgrips. The handle goes slick, you wrap a new one in the car park, you play. That is the whole catalog.",
      includes: [
        "12 × perforated overgrips",
        "Tacky, for padel (tennis too)",
        "Ships as a small parcel, not a carton of junk",
      ],
      specs: [
        ["Pack", "12 wraps"],
        ["Feel", "Tacky, perforated"],
        ["For", "Padel first. Tennis if that’s tonight."],
        ["Life", "A few sessions each, then bin it"],
      ],
      images: [
        { src: "assets/court.jpg", alt: "Night padel court, rackets on the bench" },
        { src: "assets/grips.jpg", alt: "Stack of overgrip rolls on a bench" },
        { src: "assets/wrap.jpg", alt: "Wrapping a fresh overgrip on a racket handle" },
        { src: "assets/pack.jpg", alt: "Twelve grips in a plain mailer with a padel ball" },
      ],
    },
  ],
};
